### PR TITLE
Initial user photo upload component created, with functionality pendi…

### PR DESCRIPTION
**Pull request by Techgawd**
…ng endoint. Added avatar, changed links on user dash

### CODE REVIEW

**Review by candaceyw — DISMISSED** [review]
approved with warnings, as these components were corrected in previous PR and these files were not changed in this PR.

**Review by SheilaRMoore — CHANGES_REQUESTED** [review]
Nice work on the image upload so far. I think we may need to remove useEffect, useState, and getGroomers on the GroomerCards.

**Review by SheilaRMoore — DISMISSED** [review]

**Review by candaceyw — CHANGES_REQUESTED** [review]
We've got an error coming up in checks. Can you check to see what's causing this? I'm unsure where it's happening from the PR.

**Review by prietopedro — APPROVED** [review]
Awesome work

**Review by candaceyw — APPROVED** [review]
Looks good! 👍🏼

**Pull request merged**
